Hacky Fix, Pie shows .android.camer: Accessing hidden method Landroid/hardware/camera2/marshal/MarshalRegistry;->registerMarshalQueryable(Landroid/hardware/camera2/marshal/MarshalQueryable;)V (blacklist, linking) And then throws E AndroidRuntime: java.lang.NoSuchMethodError: No static method registerMarshalQueryable(Landroid/hardware/camera2/marshal/MarshalQueryable;)V in class Landroid/hardware/camera2/marshal/MarshalRegistry; or its super classes (declaration of 'android.hardware.camera2.marshal.MarshalRegistry' appears in /system/framework/framework.jar) My current rom AOSiP contains a different implementation of this I don't know why. Therefore added a renamed implemention from MIUI. MarshalRegistryANX. Updated com.android.camera2.CaptureResultParser to use the same.